// <auto-generated />
using HomeServer.Formula1Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeServer.Formula1Database.Migrations
{
    [DbContext(typeof(Formula1Context))]
    [Migration("20260731050613_InitializeDb")]
    partial class InitializeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("HomeServer.Formula1Database.LapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LapNumber")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("LapTime")
                        .HasColumnType("REAL");

                    b.PrimitiveCollection<string>("MiniSectors1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MiniSectors2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MiniSectors3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float?>("Sector1")
                        .HasColumnType("REAL");

                    b.Property<float?>("Sector2")
                        .HasColumnType("REAL");

                    b.Property<float?>("Sector3")
                        .HasColumnType("REAL");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SpeedTrap")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TireCompound")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Laps");
                });

            modelBuilder.Entity("HomeServer.Formula1Database.MeetingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("HomeServer.Formula1Database.Models.F1DriverModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BroadcastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DriverNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeadshotUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameAcronym")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("HomeServer.Formula1Database.Models.SessionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AirPressure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CircuitKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Rainfall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrackTemp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HomeServer.Formula1Database.Models.SessionResultModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DNF")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DNS")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("DSQ")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DriverNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinishingPosition")
                        .HasColumnType("INTEGER");

                    b.Property<float>("GapToLeader")
                        .HasColumnType("REAL");

                    b.Property<int>("MeetingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumberOfPitstops")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tires")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("SessionResults");
                });
#pragma warning restore 612, 618
        }
    }
}
